# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bot-BasicBot-Pluggable-Module-RD
version:      0.01
version_from: lib/Bot/BasicBot/Pluggable/Module/RD.pm
installdirs:  site
requires:
    Bot::BasicBot::Pluggable::Module: 0
    Parse::RecDescent:             0
    Parse::RecDescent::Deparse:    0
    Parse::RecDescent::Topiary:    0.04
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
